import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.110.2';

const SUPABASE_URL='https://dlturcdfemudmwylbpqe.supabase.co';
const SUPABASE_KEY='sb_publishable_oQF52rpJyHG0AC4iJm9Vvg_hUqOgUWS';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{db:{schema:'cos'}});
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>new Intl.NumberFormat().format(Number(v||0));
const compact=v=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(v||0));
const date=v=>v?new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not available';
let state;

function pageHead(title,detail,right=''){return `<div class="page-head"><div><h2>${esc(title)}</h2><p>${esc(detail)}</p></div>${right?`<span class="quiet">${esc(right)}</span>`:''}</div>`}
function provider(name){return state.audit.providers.find(item=>item.provider===name)||{};}
function percent(value,max){return max?Math.max(3,Math.round(value/max*100)):0;}
function taskProgress(task){const tests=task.tests?.length||0, artifacts=task.artifacts?.length||0;return Math.min(92,20+tests*8+artifacts*3);}

function renderOverview(){
  const o=state.overview,claude=provider('claude'),codex=provider('codex'),tasks=state.continuity.tasks.filter(t=>t.status==='active');
  const runnerConnected=state.control_plane.local_runner==='connected';
  $('[data-panel="overview"]').innerHTML=pageHead('Operating overview','The current state of work, agents, approvals, and execution readiness.','Live Supabase aggregates · no prompt content')+`
  <div class="kpi-grid">
    <article class="kpi"><div class="kpi-top">Active work <i></i></div><strong>${o.active_work}</strong><span>Continuity tasks in progress</span></article>
    <article class="kpi"><div class="kpi-top">Pending review <em class="delta">Human gate</em></div><strong>${o.pending_review}</strong><span>Recommendations awaiting disposition</span></article>
    <article class="kpi"><div class="kpi-top">Captured tokens <i></i></div><strong>${compact(o.captured_tokens)}</strong><span>Claude only · Codex telemetry missing</span></article>
    <article class="kpi"><div class="kpi-top">Verified outcomes <i></i></div><strong>${o.verified_outcomes}</strong><span>Explicitly recorded, not inferred</span></article>
  </div>
  <div class="grid-2"><article class="card"><div class="card-head"><div><h3>Execution readiness</h3><p>What exists today versus what still needs wiring.</p></div><button class="link-button" data-go="system">View system</button></div><div class="readiness">
    ${readyRow('✓','Website control surface','Authenticated seven-tab operating console','Operational','')}
    ${readyRow('✓','Control-plane database','Work, approvals, events, metrics, and continuity are live','Operational','')}
    ${readyRow(runnerConnected?'✓':'○','Local CoS runner',runnerConnected?'Heartbeat observed in the last five minutes':'Runner registered; heartbeat is currently stale',runnerConnected?'Connected':'Offline',runnerConnected?'':'off')}
    ${readyRow('✓','Agent Architect','Opus/Sonnet/Haiku orchestration skill operational','Operational','')}
  </div></article>
  <article class="card"><div class="card-head"><div><h3>Provider activity</h3><p>Events recorded by the AI Work Audit.</p></div><button class="link-button" data-go="usage">Full usage</button></div><div class="provider-snapshot">
    ${providerLine('claude',claude.events,Math.max(claude.events||0,codex.events||0),`${number(claude.events)} events`)}
    ${providerLine('codex',codex.events,Math.max(claude.events||0,codex.events||0),`${number(codex.events)} events`)}
  </div><div class="notice">Codex token totals are not currently captured. Activity comparisons are valid; token and cost comparisons are incomplete.</div></article></div>
  <div class="grid-even"><article class="card"><div class="card-head"><div><h3>Current work</h3><p>Latest immutable checkpoints.</p></div><button class="link-button" data-go="work">Open queue</button></div><div class="work-list">${tasks.slice(0,3).map(workRow).join('')}</div></article>
  <article class="card"><div class="card-head"><div><h3>Attention needed</h3><p>The next decisions that unlock the operating system.</p></div><button class="link-button" data-go="approvals">Review gates</button></div><div class="readiness">
    ${readyRow('1','Review pending recommendations',`${o.pending_review} audit improvements need human disposition`,'Review','warn')}
    ${readyRow('2','Decide execution gates',`${o.pending_approvals} control-plane approval request${o.pending_approvals===1?'':'s'} waiting`,'Approve','warn')}
    ${readyRow('3','Restore runner heartbeat','Registered runner has not checked in recently','Reconnect','off')}
  </div></article></div>`;
}
function readyRow(icon,title,detail,status,mode){return `<div class="ready-row ${mode}"><span class="ready-icon">${icon}</span><div><strong>${esc(title)}</strong><small>${esc(detail)}</small></div><span class="status ${mode}">${esc(status)}</span></div>`}
function providerLine(name,value,max,label){return `<div class="provider-line ${name}"><strong>${esc(name)}</strong><div class="bar"><i style="width:${percent(value,max)}%"></i></div><span>${esc(label)}</span></div>`}
function workRow(task){return `<div class="work-row"><div><strong>${esc(task.objective)}</strong><p>${esc(task.next_action||'No next action recorded')}</p><div class="progress"><i style="width:${taskProgress(task)}%"></i></div></div><time>v${task.checkpoint_version||0}<br>${date(task.updated_at)}</time></div>`}

function renderWork(){const tasks=state.continuity.tasks,live=state.operations.work||[];$('[data-panel="work"]').innerHTML=pageHead('Work queue','Durable continuity tasks and executable control-plane work in one view.',`${tasks.filter(t=>t.status==='active').length} active · ${live.length} control-plane`)+`<article class="card"><div class="card-head"><div><h3>Durable work</h3><p>Latest immutable checkpoint and evidence for every continuity task.</p></div></div><table class="queue-table"><thead><tr><th>Work item</th><th>Owner</th><th>Status</th><th>Checkpoint</th><th>Evidence</th></tr></thead><tbody>${tasks.map(task=>`<tr><td><strong>${esc(task.objective)}</strong><small>Next: ${esc(task.next_action||'Not recorded')}</small></td><td>${esc(task.owner_agent)}</td><td><span class="chip">${esc(task.status)}</span></td><td>v${task.checkpoint_version||0}<small>${date(task.checkpoint_at)}</small></td><td>${task.artifacts?.length||0} artifacts<small>${task.tests?.length||0} checks · ${task.blockers?.length||0} blockers</small></td></tr>`).join('')}</tbody></table></article><article class="card" style="margin-top:14px"><div class="card-head"><div><h3>Execution ledger</h3><p>Typed work items that can move through plan, lease, run, review, and release gates.</p></div></div>${live.length?`<table class="queue-table"><thead><tr><th>Work item</th><th>Project</th><th>Priority</th><th>State</th><th>Updated</th></tr></thead><tbody>${live.map(w=>`<tr><td><strong>${esc(w.title)}</strong><small>${esc(w.description||w.work_id)}</small></td><td>${esc(w.project||'—')}</td><td>${esc(w.priority)}</td><td><span class="chip">${esc(w.state)}</span></td><td>${date(w.updated_at)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state"><strong>No executable work yet</strong><p>Continuity tracking remains available above.</p></div>'}</article>`}

function renderAgents(){const c=provider('claude'),x=provider('codex');$('[data-panel="agents"]').innerHTML=pageHead('Agents','Model roles, observed activity, and the planned orchestration hierarchy.','Runtime status is distinct from historical usage')+`<div class="agent-grid">
  ${agentCard('O','CoS Orchestrator','Claude Opus 4.8','Architecture, decomposition, arbitration, acceptance, and escalation.','primary','Configured','Not running')}
  ${agentCard('C','Claude','Sonnet / Haiku workers',`${number(c.events)} completed exchanges across ${number(c.sessions)} sessions.`,'',`${compact(c.tokens_total)} tokens`,'100% token coverage')}
  ${agentCard('X','Codex','Repository-native worker',`${number(x.events)} recorded events across ${number(x.sessions)} sessions.`,'',`${number(x.events)} events`,'Tokens not captured')}
  </div><div class="card" style="margin-top:14px"><div class="card-head"><div><h3>Model routing</h3><p>Use the least expensive model that can satisfy the packet and verification contract.</p></div></div><div class="routing-grid">
  <div class="route"><strong>Opus 4.8</strong><p>Orchestration, ambiguous architecture, conflict resolution, high-risk acceptance.</p></div><div class="route"><strong>Sonnet</strong><p>Implementation, synthesis, review, and surgical revision.</p></div><div class="route"><strong>Haiku</strong><p>Narrow recon, extraction, inventory, and deterministic tool work.</p></div><div class="route"><strong>Codex</strong><p>Repository editing, terminal execution, tests, and coding-agent workflows.</p></div>
  </div></div>`}
function agentCard(icon,title,model,detail,mode,a,b){return `<article class="agent-card ${mode}"><span class="agent-icon">${icon}</span><h3>${esc(title)}</h3><p>${esc(detail)}</p><div class="agent-meta"><div><small>Model / role</small><strong>${esc(model)}</strong></div><div><small>Observed state</small><strong>${esc(a)}</strong></div><div><small>Runtime</small><strong>${esc(b)}</strong></div><div><small>Authority</small><strong>${title==='CoS Orchestrator'?'Human-gated':'Task packet'}</strong></div></div></article>`}

function metricValue(metric){if(!metric.available)return '—';if(metric.unit==='ratio')return `${Math.round(metric.value*100)}%`;if(metric.unit==='seconds')return `${Math.round(metric.value)}s`;return Number(metric.value).toFixed(1)}
function metricTarget(metric){if(!metric.available)return 'No target';if(metric.target==null)return 'Baseline measurement';const value=metric.unit==='ratio'?`${Math.round(metric.target*100)}%`:metric.target;return `Target ${metric.direction==='lower'?'≤':'≥'} ${value}`}
function metricBar(metric){if(!metric.available||metric.target==null)return metric.available?55:0;if(metric.direction==='lower')return metric.value===0?100:Math.min(100,metric.target/metric.value*100);return Math.min(100,metric.value/metric.target*100)}
function metricCard(metric){const label=metric.status==='on_target'?'On target':metric.status==='needs_attention'?'Needs attention':metric.status==='baseline'?'Baseline':'Unavailable';return `<article class="tracker ${metric.status}"><header><span>${esc(metric.domain)}</span><span class="tracker-status">${label}</span></header><h3>${esc(metric.label)}</h3><div class="tracker-value"><strong>${metricValue(metric)}</strong><small>${esc(metricTarget(metric))}</small></div><p>${esc(metric.available?metric.source:metric.reason)}</p><div class="target-bar"><i style="width:${metricBar(metric)}%"></i></div></article>`}
function renderMetrics(){const measured=state.metrics.filter(m=>m.available),on=measured.filter(m=>m.status==='on_target'),attention=measured.filter(m=>m.status==='needs_attention'),unavailable=state.metrics.filter(m=>!m.available),outcomes=state.audit.outcomes||{},evidence=state.continuity.evidence||{};$('[data-panel="metrics"]').innerHTML=pageHead('Performance metrics','Delivery, quality, efficiency, and coverage—measured separately from raw activity.','Provisional targets · refine after 30 days')+`
  <div class="tracker-summary"><div class="summary-card"><small>Measured trackers</small><strong>${measured.length}</strong><span>Deterministic evidence available</span></div><div class="summary-card"><small>On provisional target</small><strong>${on.length}</strong><span>Baseline targets currently met</span></div><div class="summary-card"><small>Needs attention</small><strong>${attention.length}</strong><span>Measured gaps to address</span></div><div class="summary-card"><small>Not instrumented</small><strong>${unavailable.length}</strong><span>Never rendered as zero</span></div></div>
  <div class="tracker-grid">${state.metrics.map(metricCard).join('')}</div>
  <div class="grid-2"><article class="card"><div class="card-head"><div><h3>Evidence and outcomes</h3><p>Explicit operational proof, not inferred productivity.</p></div></div><div class="usage-numbers"><div><small>Checkpoints</small><strong>${number(evidence.checkpoints)}</strong></div><div><small>Artifacts</small><strong>${number(evidence.artifacts)}</strong></div><div><small>Tests recorded</small><strong>${number(evidence.tests)}</strong></div></div><div class="usage-numbers"><div><small>Outcome records</small><strong>${number(outcomes.records)}</strong></div><div><small>Retries</small><strong>${number(outcomes.retries)}</strong></div><div><small>Recoveries</small><strong>${number(outcomes.recoveries)}</strong></div></div></article><article class="card"><div class="card-head"><div><h3>Checkpoint cadence</h3><p>Immutable checkpoints written by week.</p></div></div>${checkpointChart(state.continuity.checkpoint_weekly||[])}</article></div>
  <div class="card" style="margin-top:14px"><div class="card-head"><div><h3>Instrumentation backlog</h3><p>Build these before claiming cost efficiency or control-plane reliability.</p></div></div><div class="instrument-grid">${instrument(1,'Codex token capture','Record input/output usage on completed Stop-hook exchanges.')}${instrument(2,'Task-linked model calls','Attach task, run, role, and model-call IDs.')}${instrument(3,'Actual cost ledger','Store price-version and actual call cost.')}${instrument(4,'Review outcomes','Record findings, revision rounds, and final verdict.')}${instrument(5,'Cycle and approval time','Add task start and completion timestamps.')}${instrument(6,'Runner reliability','Retain heartbeat history, leases, expiry, and recovery.')}</div></div>`}
function instrument(n,title,detail){return `<div class="instrument"><span>${n}</span><strong>${esc(title)}</strong><p>${esc(detail)}</p></div>`}
function checkpointChart(items){const max=Math.max(...items.map(x=>x.checkpoints),1);return `<div class="mini-chart">${items.slice(-10).map(x=>`<div class="mini-week"><i style="height:${Math.max(3,x.checkpoints/max*100)}px"></i><small>${esc(x.week.slice(5))}</small></div>`).join('')}</div>`}

function renderUsage(){const providers=state.audit.providers,maxEvents=Math.max(...providers.map(p=>p.events),1);$('[data-panel="usage"]').innerHTML=pageHead('Usage & telemetry','Claude and Codex activity with honest token-coverage boundaries.','Tokens are activity, not productivity')+`<div class="usage-hero">${providers.map(p=>`<article class="usage-provider"><header><strong>${esc(p.provider)}</strong><span>${p.tokens_available?'Token telemetry available':'Token telemetry unavailable'}</span></header><div class="usage-numbers"><div><small>Events</small><strong>${number(p.events)}</strong></div><div><small>Sessions</small><strong>${number(p.sessions)}</strong></div><div><small>Total tokens</small><strong>${p.tokens_available?compact(p.tokens_total):'—'}</strong></div></div><div class="coverage">Token coverage · ${Math.round(p.token_coverage*100)}%<div class="progress"><i style="width:${Math.max(1,p.token_coverage*100)}%;background:${p.provider==='codex'?'var(--blue)':'var(--green)'}"></i></div></div></article>`).join('')}</div>
  <div class="grid-2"><article class="card"><div class="card-head"><div><h3>Weekly event activity</h3><p>Provider events by week. Codex token totals remain unavailable.</p></div></div>${weeklyChart(state.audit.weekly)}</article><article class="card"><div class="card-head"><div><h3>Telemetry coverage</h3><p>What can be compared safely today.</p></div></div><div class="readiness">${readyRow('✓','Claude activity and tokens','Complete response and token coverage','Comparable','')}${readyRow('✓','Codex activity','Prompt/event counts and sessions available','Comparable','')}${readyRow('!','Codex tokens and outcomes','Add Stop-hook usage and explicit outcome instrumentation','Missing','warn')}${readyRow('○','Cost totals','No stable per-call cost ledger yet','Not captured','off')}</div></article></div>
  <div class="grid-2"><article class="card"><div class="card-head"><div><h3>Model usage</h3><p>Events and captured tokens by observed model.</p></div></div>${modelTable(state.audit.models||[])}</article><article class="card"><div class="card-head"><div><h3>Project activity</h3><p>Top normalized workspaces by event count.</p></div></div>${projectBars(state.audit.projects||[])}</article></div>`}
function weeklyChart(items){const weeks=[...new Set(items.map(x=>x.week_start))].slice(-10),by=(w,p)=>items.find(x=>x.week_start===w&&x.provider===p)?.events||0,max=Math.max(...items.map(x=>x.events),1);return `<div class="chart">${weeks.map(w=>`<div class="week"><div class="week-bars"><i style="height:${Math.max(2,by(w,'claude')/max*130)}px"></i><i class="codex" style="height:${Math.max(2,by(w,'codex')/max*130)}px"></i></div><small>${w.slice(5)}</small></div>`).join('')}</div><div class="legend-line"><span style="color:var(--green)">● Claude</span> <span style="color:var(--blue)">● Codex</span></div>`}
function modelTable(items){return `<table class="model-table"><thead><tr><th>Provider / model</th><th>Events</th><th>Input</th><th>Output</th><th>Total</th></tr></thead><tbody>${items.map(m=>`<tr><td><strong>${esc(m.provider)}</strong><br>${esc(m.model)}</td><td>${number(m.events)}</td><td>${m.tokens_available?compact(m.tokens_in):'—'}</td><td>${m.tokens_available?compact(m.tokens_out):'—'}</td><td>${m.tokens_available?compact(m.tokens_total):'Not captured'}</td></tr>`).join('')}</tbody></table>`}
function projectBars(items){const max=Math.max(...items.map(x=>x.events),1);return `<div class="project-bars">${items.map(p=>`<div class="project-bar"><strong>${esc(p.project)}</strong><div class="bar"><i style="width:${percent(p.events,max)}%;background:var(--green)"></i></div><span>${number(p.events)}</span></div>`).join('')}</div>`}

function renderApprovals(){const recs=state.audit.recommendations.filter(r=>r.status==='proposed'),gates=state.operations.approvals||[];$('[data-panel="approvals"]').innerHTML=pageHead('Approvals & human gates','Recommendations and executable gates remain separate, explicit decisions.',`${recs.length} recommendations · ${gates.length} execution gates`)+`<div class="grid-2"><article class="card"><div class="card-head"><div><h3>Execution approvals</h3><p>Approve or reject the exact stored plan hash.</p></div></div>${gates.length?`<div class="approval-list">${gates.map(a=>`<div class="approval-row"><i class="priority-dot high"></i><div><strong>${esc(a.title||a.work_id)}</strong><p>${esc(a.gate_type)} gate · hash ${esc((a.payload_hash||'').slice(0,12))}… · ${date(a.requested_at)}</p></div><div class="action-buttons"><button class="action-button approve" data-approval="${esc(a.approval_id)}" data-decision="true">Approve</button><button class="action-button reject" data-approval="${esc(a.approval_id)}" data-decision="false">Reject</button></div></div>`).join('')}</div>`:'<div class="empty-state"><strong>No execution approvals waiting</strong><p>The queue is connected and currently clear.</p></div>'}</article><article class="card"><div class="card-head"><div><h3>Recommendation review queue</h3><p>AI Work Audit recommendations remain human-gated.</p></div></div><div class="approval-list">${recs.map(r=>`<div class="approval-row"><i class="priority-dot ${esc(r.priority)}"></i><div><strong>${esc(r.title)}</strong><p>${esc(r.category)} · ${esc(r.priority)} priority · targets ${esc((r.target_agents||[]).join(', ')||'unassigned')}</p></div><span class="chip">Proposed</span></div>`).join('')}</div></article></div><div class="card" style="margin-top:14px"><div class="card-head"><div><h3>Gate model</h3><p>Plan, sensitive-action, and release authority are distinct.</p></div></div><div class="gate-grid"><div class="gate"><span>1</span><strong>Plan approval</strong><p>Objective, scope, models, tools, budget, and ownership.</p></div><div class="gate"><span>2</span><strong>Sensitive action</strong><p>Credentials, production data, external messages, financial, or destructive steps.</p></div><div class="gate"><span>3</span><strong>Release approval</strong><p>The exact reviewed artifact or commit hash after verification.</p></div></div></div>`}

function renderSystem(){const connected=state.control_plane.local_runner==='connected',runners=state.operations.runners||[],events=state.operations.events||[];$('[data-panel="system"]').innerHTML=pageHead('System architecture','The website controls authority. The database coordinates. The local computer executes.','Website ↔ Database ↔ Local')+`<div class="system-board"><svg class="system-svg" viewBox="0 0 1100 520" aria-hidden="true"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L7 3L0 6Z" fill="#2e6b3f"/></marker><marker id="b" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L7 3L0 6Z" fill="#477c9b"/></marker></defs><path d="M300 155C470 70 650 68 790 115" fill="none" stroke="#2e6b3f" stroke-width="2.5" marker-end="url(#a)"/><path d="M790 178C620 245 475 250 300 205" fill="none" stroke="#b87332" stroke-width="2.5"/><path d="M255 250C320 340 430 370 520 382" fill="none" stroke="#477c9b" stroke-width="2.5" marker-end="url(#b)"/></svg><div class="sys-node db"><small>Durable go-between</small><strong>Supabase Control Plane</strong><span>Typed jobs, approvals, leases, decisions, artifacts, usage, and outcomes.</span></div><div class="sys-node web"><small>Human authority</small><strong>CS Ventures Website</strong><span>Create work, approve plans, monitor progress, review evidence, authorize release.</span></div><div class="sys-node local"><small>Trusted execution</small><strong>Local CoS Runner</strong><span>Claims approved jobs and invokes Claude and Codex through local tools.</span></div><div class="system-note">× No direct website-to-laptop command channel</div></div><div class="grid-even"><article class="card"><div class="card-head"><div><h3>Current readiness</h3><p>Measured from the live control plane.</p></div></div><div class="readiness">${readyRow('✓','Website console','Authenticated dashboard is Supabase-backed','Operational','')}${readyRow('✓','Database control plane','Typed ledger and owner-gated APIs are deployed','Operational','')}${readyRow(connected?'✓':'○','Local runner',connected?'Heartbeat is current':`${runners.length} runner registered; latest heartbeat is stale`,connected?'Connected':'Offline',connected?'':'off')}</div></article><article class="card"><div class="card-head"><div><h3>Recent control-plane events</h3><p>Append-only transitions from the execution ledger.</p></div></div><div class="event-list">${events.length?events.slice(0,8).map(e=>`<div class="event-row"><time>${date(e.created_at)}</time> · ${esc(e.actor)} · <strong>${esc(e.event_type)}</strong>${e.prior_state?` · ${esc(e.prior_state)} → ${esc(e.new_state)}`:''}</div>`).join(''):'<div class="empty-state"><strong>No events yet</strong></div>'}</div></article></div>`}

function bindNavigation(){
  $$('[data-tab]').forEach(button=>button.onclick=()=>activate(button.dataset.tab));
  $$('[data-go]').forEach(button=>button.onclick=()=>activate(button.dataset.go));
  $$('[data-approval]').forEach(button=>button.onclick=()=>decideApproval(button.dataset.approval,button.dataset.decision==='true'));
}
function activate(tab,updateHash=true){if(!$(`[data-panel="${tab}"]`))return;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===tab));if(updateHash)history.replaceState(null,'',`#${tab}`);window.scrollTo({top:0,behavior:'smooth'})}
function render(){
  $('#loading').style.display='none';$('#updated-at').textContent=date(state.generated_at);$('#work-count').textContent=state.overview.active_work;$('#approval-count').textContent=state.overview.pending_review+state.overview.pending_approvals;$('#metric-count').textContent=state.metrics.filter(m=>m.status==='needs_attention').length;
  const connected=state.control_plane.local_runner==='connected';$('#runner-pill').classList.toggle('connected',connected);$('#runner-pill').innerHTML=`<i></i> ${connected?'Local runner connected':'Local runner offline'}`;
  renderOverview();renderMetrics();renderWork();renderAgents();renderUsage();renderApprovals();renderSystem();bindNavigation();activate(location.hash.slice(1)||'overview',false);
}
async function load(){const{data,error}=await sb.rpc('api_dashboard_state');if(error)throw error;state=data;render()}
async function decideApproval(id,approved){if(!confirm(`${approved?'Approve':'Reject'} this execution gate?`))return;const{error}=await sb.rpc('api_decide_approval',{p_approval_id:id,p_approved:approved,p_note:'Decided from CS Ventures control dashboard'});if(error){alert(`Action failed: ${error.message}`);return}await load()}
function showApp(session){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#who').textContent=session.user.email;load().catch(error=>{$('#loading').className='loading-error';$('#loading').textContent=`Could not load dashboard data: ${error.message}`})}
function showLogin(){$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();$('#loginErr').textContent='';const{data,error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){$('#loginErr').textContent='Invalid email or password.';return}showApp(data.session)});
$('#signout').addEventListener('click',async()=>{await sb.auth.signOut();showLogin()});
$('#refresh').addEventListener('click',async()=>{const b=$('#refresh');b.textContent='Refreshing…';try{await load();b.textContent='Data refreshed'}catch(error){b.textContent='Refresh failed'}setTimeout(()=>b.textContent='Refresh data',1200)});
const{data:{session}}=await sb.auth.getSession();if(session)showApp(session);else showLogin();
